### ISSUE TITLE
Một số vấn đề chậm / thiếu data

### ISSUE THREAD

**Issue by VietPhamDatamart** [tikivn/open-api-docs#131]
Hi, mình từ bên PowerSell (Datamart), đang muốn kết nối vào Tiki để hỗ trợ các nhà bán hàng quản lý gian hàng của họ.

Trước hết rất cám ơn nỗ lực xây dựng hệ thống cũng như tài liệu chuẩn và đầy đủ của anh em kĩ thuật Tiki. Mình mới tham khảo và dùng thử qua một số API và thấy có hoạt động rõ ràng.

Sơ qua, mình có nhìn thấy một số vấn đề nhỏ mà nếu khắc phục được thì sẽ dẫn đến việc kết nối ổn định và dễ cho bên thứ ba sử dụng hơn:
- Đối với API lấy orders, thì API này trả về tương đối chậm. Mình lấy 50 đơn hàng mà mất đến 10s mới trả về kết quả. Thậm chí là nhiều lúc còn trả về lỗi timeout.
- Ngoài ra, API lấy orders có vẻ chưa ổn định, tức là không phải lúc nào cũng trả đúng kết quả, có lúc trả về là một danh sách rỗng. Điều này có thể dẫn đến lầm tưởng là không có đơn hàng.
- Với API cập nhật sản phẩm, yêu cần input là original_sku. Tuy nhiên theo mình hiểu thì original_sku là không bắt buộc phải có đối với một sản phẩm. Như vậy trong trường hợp nhà bán hàng không nhập original_sku thì làm thế nào để dùng API cập nhật (đối giá/tồn kho chẳng hạn).

Anh em kĩ thuật Tiki check hộ mình xem những vấn đề trên có xử lý được không, và giải pháp tương ứng như thế nào. Nếu liên quan đến việc chỉnh sửa hệ thống thì anh em có biết sẽ mất khoảng bao lâu không ạ.

Cám ơn mọi người nhiều.

Best.

**Comment by ducanhnguyen19** [comment]
Thank for your feedback 
- Due to the unstable of order API , we will improve it and tell you once it done . Because order is a complex business affect to many team so sometimes it can take longer than usual , so please sympathize with us
- Update API endpoint is using `original_sku` it is required when you create product , you can read from here : https://open.tiki.vn/#create-new-product-request . So you should log `original_sku` in your side to update product later . In the next sprint we will try to release update by TIKI `product_id` for seller so maybe you can update via that endpoint 

Thank you

**Comment by VietPhamDatamart** [comment]
Thank you so much for your prompt response! Please let us know when the problem with unstable order API is fixed.

Also, I am aware that `original_sku` must be provided when creating product via API. But is it required when a seller creates his/her own product on seller center website?

**Comment by hungsmcc** [comment]
"In the next sprint we will try to release update by TIKI product_id for seller so maybe you can update via that endpoint." Thank you and tiki marketplace team.

May we have an estimated time for this fearture. It is so significant to update by product_id because of the fact that almost tiki's product data doesn't has original_sku (seller_sku).

**Comment by ducanhnguyen19** [comment]
@hungsmcc okay we will try to release update by TIKI `product_id` in the next week , keep calm and wait for us , thank you :D

**Comment by hungsmcc** [comment]
@ducanhnguyen19 Almost 1 month has passed, is there any news yet for this issue?
This feature is really important for our product plan, thanks

**Comment by vietcaominh** [comment]
hi @hungsmcc we have released the function enable update product by product_id here https://open.tiki.vn/#update-variant-price-quantity-active. Go to the link for more details
