### ISSUE TITLE
Which order status can we print order label (seller delivery or cross_border)

### ISSUE THREAD

**Issue by hungsmcc** [tikivn/open-api-docs#151]

**Comment by vietcaominh** [comment]
hi @hungsmcc. Only two types of orders can call get print order label API. They are seller_delivery AND cross_border.
Let us know if you have further questions.

**Comment by hungsmcc** [comment]
Thanks, however I mean the order status of order not type of order.
More specifically, is "Order label" is available when the order status is under: "canceled", "complete", "delivered". Or is it only fetchable if order status is "packaging" or "finished_packing".

**Comment by vietcaominh** [comment]
hi @hungsmcc .
Currently, we only check the fulfillment type for Get label API. Can you give us orders code example that you can't call Get label with those types we mentioned above?
If it is the order you posted in [here](https://github.com/tikivn/open-api-docs/issues/152#issuecomment-604791974) 
It is because the fulfillment type is empty so we throw an error back to you. We will address this problem on that ticket.

**Comment by hungsmcc** [comment]
understood, thanks very much
