### ISSUE TITLE
[Datamart] Order status changing flow on sandbox env

### ISSUE THREAD

**Issue by hungsmcc** [tikivn/open-api-docs#155]
I did some calls on order' API series:

//step 1: get an order details
```
GET /integration/v1/orders/789201846-SfgQNE HTTP/1.1
Host: api-sandbox.tiki.vn
Content-Type: application/json
Tiki-Api: 55f438d1-3438-409e-b5a4-9d16e764c5b8

{"order_code":"789201846-SfgQNE","coupon_code":"GIAMGIALON","status":"queueing","total_price_before_discount":380000,"total_price_after_discount":342000,"created_at":null,"updated_at":"2019-11-18 10:43:44","purchased_at":"2019-11-18 10:43:43","fulfillment_type":"seller_delivery","note":"","deliveryConfirmed":"","delivery_confirmed_at":"2019-11-18 10:58:06","is_rma":0,"tax":{"code":null,"name":null,"address":null},"discount":{"discou...
```

//step 2: confirm the order
```
POST /integration/v1/orders/confirmItems HTTP/1.1
Host: api-sandbox.tiki.vn
Content-Type: application/json
Tiki-Api: 55f438d1-3438-409e-b5a4-9d16e764c5b8

{"delivery_commitment_time":"2019-11-03 23:59:59","item_ids":[[25228527,25228528]],"order_code":"789201846-SfgQNE","tracking_number":"789201846-SfgQNE","warehouse_id":123}

{"code":200,"data":[]}
```

//step 3: get the order details again
```
GET /integration/v1/orders/789201846-SfgQNE HTTP/1.1
Host: api-sandbox.tiki.vn
Content-Type: application/json
Tiki-Api: 55f438d1-3438-409e-b5a4-9d16e764c5b8

{"order_code":"789201846-SfgQNE","coupon_code":"GIAMGIALON","status":"canceled",...
```

//step 4: update delivery status
```
POST /integration/v1/orders/updateDeliveryStatus HTTP/1.1
Host: api-sandbox.tiki.vn
Content-Type: application/json
Tiki-Api: 55f438d1-3438-409e-b5a4-9d16e764c5b8

{"order_code":"789201846-SfgQNE","status":"ready_for_delivery","update_time":"2020-04-08 12:25:50"}

{"message":"success"}
```

//step 5: get the order details one more time
```
GET /integration/v1/orders/789201846-SfgQNE HTTP/1.1
Host: api-sandbox.tiki.vn
Content-Type: application/json
Tiki-Api: 55f438d1-3438-409e-b5a4-9d16e764c5b8

{"order_code":"789201846-SfgQNE","coupon_code":"GIAMGIALON","status":"ready_for_delivery",... 
```

As you see the order's status is changed as: queueing -> canceled -> ready_for_delivery
(order's "fulfillment_type":"seller_delivery")

Is that normal or it only happens on sandbox env.

And one more problem, is that products (product_id) coming from sandbox test orders do not exist.
Product 1:
```
GET /integration/v1/products/2049354 HTTP/1.1
Host: api-sandbox.tiki.vn
Content-Type: application/json
Tiki-Api: 55f438d1-3438-409e-b5a4-9d16e764c5b8

{"errors":["product not found"]}
```

Product 2:
```
GET /integration/v1/products/2137869 HTTP/1.1
Host: api-sandbox.tiki.vn
Content-Type: application/json
Tiki-Api: 55f438d1-3438-409e-b5a4-9d16e764c5b8

{"errors":["product not found"]}
```

**Comment by vietcaominh** [comment]
hi @hungsmcc about the order status changed wrongly. it's only happen on sandbox, because multiple users using the same tiki-api now. We're developing a new mock order system, will release it shortly after that the order status problem will go away.
About the get product details by product_id get not found error. This is because in sandbox there is no admin and system to active your product yet. So for now, please using the production environment to test product related tasks.

**Comment by hungsmcc** [comment]
Thanks, i understood about the order status problem.

> About the get product details by product_id get not found error. This is because in sandbox there is no admin and system to active your product yet. So for now, please using the production environment to test product related tasks.

However, they are not my product, they comes with test orders which should exist. I think it is another error of the mock order system.

**Comment by vietcaominh** [comment]
hi @hungsmcc . Sorry for the late reply.
The product_id not found is a problem due to the limitation of the current mock order also.
Because the products in the sample do not belong to seller have the tiki-api use for testing on sandbox. That why you can't get product details for those Ids.
Please don't try to get details of product_id in mock orders. You can get details of the product you created with the create product request endpoint.
