### ISSUE TITLE
Vấn đề đơn trả về không tồn tại trên phần mềm Tiki

### ISSUE THREAD

**Issue by Hungpx** [tikivn/open-api-docs#184]
ID đơn Tiki 771147359, Seller: DOF.zone. Doanh nghiệp báo lại khi tải api về thì có đơn này đang ở trạng thái waiting_payment, tuy nhiên thì tìm trên TIKI không thấy đơn này. Phiền team check lại giúp em với ạ

**Comment by vietcaominh** [comment]
Hi @Hungpx . We confirmed your problem. Let us investigate why it happened. Please wait for us.

**One small notes: Please use English to create Github issue and when chatting with us, because we have a lot of foreigner sellers using open API also, so all people can see their problem already have been asked if it exists before firing an issue**
Please help us to create a good community! Many thanks

**Comment by hoai-dam** [comment]
Hello @Hungpx,

This order payment failed, therefore it is not considered a successful purchase and is not displayed to the seller on Seller Center.

FYI.

**Comment by Hungpx** [comment]
> Hello @Hungpx,
> 
> This order payment failed, therefore it is not considered a successful purchase and is not displayed to the seller on Seller Center.
> 
> FYI.
============================================>
Nếu không hiển hiện cho người bán xem thì có thể check lại api không trả về những đơn này nữa được không ạ?

**Comment by tuhucon** [comment]
Sorry all, I closed this issue.
Please use English.

**Comment by Hungpx** [comment]
please check again before close this issue. Thanks
