### ISSUE TITLE
[Crossborder]

### ISSUE THREAD

**Issue by chrkyrong** [tikivn/open-api-docs#219]
![image](https://user-images.githubusercontent.com/39123190/84361595-7cad5a80-abfe-11ea-922f-2450378e0f6c.png)

**Comment by vietcaominh** [comment]
Hi @chrkyrong . Mock orders only support on Sandbox environment for support testing, because in Sandbox, our system is the customer side is not ready to open. So you cannot create the orders to test so that why we created this endpoint.
On production, the orders created when a customer place order on tiki.vn, and those are real orders. So we cannot support create mock orders on production because it will mess up our system.

**Comment by vietcaominh** [comment]
And please specify your questions in words for next time. Otherwise, we will not answer
