### ISSUE TITLE
Issue about wrong sum of orders on /orders endpoint

### ISSUE THREAD

**Issue by tnohtition** [tikivn/open-api-docs#232]
Hi, tiki development team. I am very happy if you could help me something about the issue below

I have called a request like this
# https://api.tiki.vn/integration/v1/orders?status=all&page=1&limit=20

The paging part tells me about the number of orders, but when I fetched over each round, the length of returning data is wrong. Each round give me the arbitrary number of data 18, 14, 15, 16, .etc. Please give me a help!

**Comment by vietcaominh** [comment]
hi @tnohtition tno

We're very sorry for the inconvenience.

This is an error in our order processing flow to wrongly count orders in each page. But no order is missing due to this. All Tiki-accepted orders are visible in the API response. We will try to work on this as soon as possible.

For now when you query orders at order listing endpoint, please use the last_page value to scan for all pages of orders that satisfy your filter.

**Comment by hoai-dam** [comment]
Order API V2 is out now at https://open.tiki.vn/#get-list-orders-v2-common-use-cases
Please take a look. We're closing this issue.
