### ISSUE TITLE
Mapping cho status trả về trong API lấy thông tin ĐH ?

### ISSUE THREAD

**Issue by simzen85** [tikivn/open-api-docs#66]
https://open.tiki.vn/#api-get-order-detail API này có trả về "status" trong response, nhờ team chia sẻ danh sách các status và mapping qua text nếu có. Thanks.

**Comment by ducanhnguyen19** [comment]
order status currently have only 4 status : 

- queueing  / new order wait for confirm / đơn hàng mới tạo cần được confirm        
- seller_confirmed  / seller confirmed this order before / seller đã confirm đơn hàng
- seller_canceled / seller canceled this order because of some reason / seller huỷ đơn hàng vì lí do nào đó 
- complete  / product is delivered to customer / đơn hàng đã giao tới tay khách hàng     

You can refer to this url for more detail : https://open.tiki.vn/#order-status 
Thanks

**Comment by ducanhnguyen19** [comment]
you can see detail in this link : https://open.tiki.vn/#order-status
if you still have any question , feel free to ask here :D

**Comment by simzen85** [comment]
tks @ducanhnguyen19 :D
